# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\nocrater\PycharmProjects\Shelter\uis\animal.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_animal(object):
    def setupUi(self, animal):
        animal.setObjectName("animal")
        animal.resize(584, 561)
        self.verticalLayout = QtWidgets.QVBoxLayout(animal)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(animal)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.name_edit = QtWidgets.QLineEdit(animal)
        self.name_edit.setObjectName("name_edit")
        self.horizontalLayout_2.addWidget(self.name_edit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(animal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.description = QtWidgets.QPlainTextEdit(animal)
        self.description.setObjectName("description")
        self.horizontalLayout_3.addWidget(self.description)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_5.setContentsMargins(-1, -1, -1, 20)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setContentsMargins(-1, -1, -1, 20)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_3 = QtWidgets.QLabel(animal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(130, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_7.addWidget(self.label_3)
        self.species_combo_box = QtWidgets.QComboBox(animal)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.species_combo_box.setFont(font)
        self.species_combo_box.setObjectName("species_combo_box")
        self.species_combo_box.addItem("")
        self.species_combo_box.addItem("")
        self.verticalLayout_7.addWidget(self.species_combo_box)
        self.horizontalLayout_5.addLayout(self.verticalLayout_7)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(-1, -1, -1, 20)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_4 = QtWidgets.QLabel(animal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(130, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_6.addWidget(self.label_4)
        self.state_combo_box = QtWidgets.QComboBox(animal)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.state_combo_box.setFont(font)
        self.state_combo_box.setObjectName("state_combo_box")
        self.state_combo_box.addItem("")
        self.state_combo_box.addItem("")
        self.state_combo_box.addItem("")
        self.state_combo_box.addItem("")
        self.verticalLayout_6.addWidget(self.state_combo_box)
        self.horizontalLayout_5.addLayout(self.verticalLayout_6)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(-1, -1, -1, 20)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_5 = QtWidgets.QLabel(animal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(130, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.where_now_combo_box = QtWidgets.QComboBox(animal)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.where_now_combo_box.setFont(font)
        self.where_now_combo_box.setObjectName("where_now_combo_box")
        self.where_now_combo_box.addItem("")
        self.where_now_combo_box.addItem("")
        self.verticalLayout_5.addWidget(self.where_now_combo_box)
        self.horizontalLayout_5.addLayout(self.verticalLayout_5)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ok_button = QtWidgets.QPushButton(animal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ok_button.sizePolicy().hasHeightForWidth())
        self.ok_button.setSizePolicy(sizePolicy)
        self.ok_button.setMinimumSize(QtCore.QSize(100, 0))
        self.ok_button.setObjectName("ok_button")
        self.horizontalLayout.addWidget(self.ok_button)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(animal)
        self.species_combo_box.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(animal)

    def retranslateUi(self, animal):
        _translate = QtCore.QCoreApplication.translate
        animal.setWindowTitle(_translate("animal", "Dialog"))
        self.label.setText(_translate("animal", "Name:   "))
        self.label_2.setText(_translate("animal", "Description:"))
        self.label_3.setText(_translate("animal", "Species:"))
        self.species_combo_box.setCurrentText(_translate("animal", "Cat"))
        self.species_combo_box.setItemText(0, _translate("animal", "Cat"))
        self.species_combo_box.setItemText(1, _translate("animal", "Dog"))
        self.label_4.setText(_translate("animal", "State:"))
        self.state_combo_box.setItemText(0, _translate("animal", "Healthy"))
        self.state_combo_box.setItemText(1, _translate("animal", "Sick"))
        self.state_combo_box.setItemText(2, _translate("animal", "Vaccine need"))
        self.state_combo_box.setItemText(3, _translate("animal", "Sick and vaccine need"))
        self.label_5.setText(_translate("animal", "Where now:"))
        self.where_now_combo_box.setItemText(0, _translate("animal", "Housing"))
        self.where_now_combo_box.setItemText(1, _translate("animal", "Clinic"))
        self.ok_button.setText(_translate("animal", "OK"))
