# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\nocrater\PycharmProjects\Shelter\uis\client.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_client(object):
    def setupUi(self, client):
        client.setObjectName("client")
        client.resize(802, 773)
        self.verticalLayout = QtWidgets.QVBoxLayout(client)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(client)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.name_edit = QtWidgets.QLineEdit(client)
        self.name_edit.setObjectName("name_edit")
        self.horizontalLayout_2.addWidget(self.name_edit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, -1, -1, 10)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.to_give = QtWidgets.QLabel(client)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.to_give.sizePolicy().hasHeightForWidth())
        self.to_give.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.to_give.setFont(font)
        self.to_give.setObjectName("to_give")
        self.verticalLayout_4.addWidget(self.to_give)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.add_to_give = QtWidgets.QPushButton(client)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.add_to_give.setFont(font)
        self.add_to_give.setObjectName("add_to_give")
        self.horizontalLayout_3.addWidget(self.add_to_give)
        self.delete_to_give = QtWidgets.QPushButton(client)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.delete_to_give.setFont(font)
        self.delete_to_give.setObjectName("delete_to_give")
        self.horizontalLayout_3.addWidget(self.delete_to_give)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.tableWidget_to_give = QtWidgets.QTableWidget(client)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_to_give.sizePolicy().hasHeightForWidth())
        self.tableWidget_to_give.setSizePolicy(sizePolicy)
        self.tableWidget_to_give.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_to_give.setColumnCount(2)
        self.tableWidget_to_give.setObjectName("tableWidget_to_give")
        self.tableWidget_to_give.setRowCount(0)
        self.tableWidget_to_give.horizontalHeader().setDefaultSectionSize(385)
        self.tableWidget_to_give.horizontalHeader().setMinimumSectionSize(70)
        self.horizontalLayout_13.addWidget(self.tableWidget_to_give)
        self.verticalLayout_4.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_9.addLayout(self.verticalLayout_4)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.to_take = QtWidgets.QLabel(client)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.to_take.sizePolicy().hasHeightForWidth())
        self.to_take.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.to_take.setFont(font)
        self.to_take.setObjectName("to_take")
        self.verticalLayout_2.addWidget(self.to_take)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.add_to_take = QtWidgets.QPushButton(client)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.add_to_take.setFont(font)
        self.add_to_take.setObjectName("add_to_take")
        self.horizontalLayout_15.addWidget(self.add_to_take)
        self.delete_to_take = QtWidgets.QPushButton(client)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.delete_to_take.setFont(font)
        self.delete_to_take.setObjectName("delete_to_take")
        self.horizontalLayout_15.addWidget(self.delete_to_take)
        self.verticalLayout_2.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.tableWidget_to_take = QtWidgets.QTableWidget(client)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_to_take.sizePolicy().hasHeightForWidth())
        self.tableWidget_to_take.setSizePolicy(sizePolicy)
        self.tableWidget_to_take.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_to_take.setColumnCount(2)
        self.tableWidget_to_take.setObjectName("tableWidget_to_take")
        self.tableWidget_to_take.setRowCount(0)
        self.tableWidget_to_take.horizontalHeader().setDefaultSectionSize(385)
        self.tableWidget_to_take.horizontalHeader().setMinimumSectionSize(70)
        self.horizontalLayout_16.addWidget(self.tableWidget_to_take)
        self.verticalLayout_2.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_9.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ok_button = QtWidgets.QPushButton(client)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ok_button.sizePolicy().hasHeightForWidth())
        self.ok_button.setSizePolicy(sizePolicy)
        self.ok_button.setMinimumSize(QtCore.QSize(100, 0))
        self.ok_button.setObjectName("ok_button")
        self.horizontalLayout.addWidget(self.ok_button)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(client)
        QtCore.QMetaObject.connectSlotsByName(client)

    def retranslateUi(self, client):
        _translate = QtCore.QCoreApplication.translate
        client.setWindowTitle(_translate("client", "Dialog"))
        self.label.setText(_translate("client", "Name:   "))
        self.to_give.setText(_translate("client", "Animals to give:"))
        self.add_to_give.setText(_translate("client", "Add"))
        self.delete_to_give.setText(_translate("client", "Delete"))
        self.to_take.setText(_translate("client", "Animals to take:"))
        self.add_to_take.setText(_translate("client", "Add"))
        self.delete_to_take.setText(_translate("client", "Delete"))
        self.ok_button.setText(_translate("client", "OK"))
