# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\nocrater\PycharmProjects\Shelter\uis\main.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main(object):
    def setupUi(self, main):
        main.setObjectName("main")
        main.resize(800, 709)
        self.centralwidget = QtWidgets.QWidget(main)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 25, -1, 25)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.main_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.main_label.setFont(font)
        self.main_label.setAlignment(QtCore.Qt.AlignCenter)
        self.main_label.setWordWrap(False)
        self.main_label.setObjectName("main_label")
        self.horizontalLayout.addWidget(self.main_label)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 25, -1, 25)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.humans_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.humans_button.sizePolicy().hasHeightForWidth())
        self.humans_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.humans_button.setFont(font)
        self.humans_button.setObjectName("humans_button")
        self.horizontalLayout_2.addWidget(self.humans_button)
        self.clients_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clients_button.sizePolicy().hasHeightForWidth())
        self.clients_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.clients_button.setFont(font)
        self.clients_button.setObjectName("clients_button")
        self.horizontalLayout_2.addWidget(self.clients_button)
        self.employees_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.employees_button.sizePolicy().hasHeightForWidth())
        self.employees_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.employees_button.setFont(font)
        self.employees_button.setObjectName("employees_button")
        self.horizontalLayout_2.addWidget(self.employees_button)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 25, -1, 25)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.animals_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.animals_button.sizePolicy().hasHeightForWidth())
        self.animals_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.animals_button.setFont(font)
        self.animals_button.setObjectName("animals_button")
        self.horizontalLayout_3.addWidget(self.animals_button)
        self.animal_cards_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.animal_cards_button.sizePolicy().hasHeightForWidth())
        self.animal_cards_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.animal_cards_button.setFont(font)
        self.animal_cards_button.setObjectName("animal_cards_button")
        self.horizontalLayout_3.addWidget(self.animal_cards_button)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 25, -1, 25)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.housings_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.housings_button.sizePolicy().hasHeightForWidth())
        self.housings_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.housings_button.setFont(font)
        self.housings_button.setObjectName("housings_button")
        self.horizontalLayout_4.addWidget(self.housings_button)
        self.clinics_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clinics_button.sizePolicy().hasHeightForWidth())
        self.clinics_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.clinics_button.setFont(font)
        self.clinics_button.setObjectName("clinics_button")
        self.horizontalLayout_4.addWidget(self.clinics_button)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, 25, -1, 25)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.positions_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.positions_button.sizePolicy().hasHeightForWidth())
        self.positions_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.positions_button.setFont(font)
        self.positions_button.setObjectName("positions_button")
        self.horizontalLayout_5.addWidget(self.positions_button)
        self.shelter_positions_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shelter_positions_button.sizePolicy().hasHeightForWidth())
        self.shelter_positions_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.shelter_positions_button.setFont(font)
        self.shelter_positions_button.setObjectName("shelter_positions_button")
        self.horizontalLayout_5.addWidget(self.shelter_positions_button)
        self.clinic_positions_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clinic_positions_button.sizePolicy().hasHeightForWidth())
        self.clinic_positions_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.clinic_positions_button.setFont(font)
        self.clinic_positions_button.setObjectName("clinic_positions_button")
        self.horizontalLayout_5.addWidget(self.clinic_positions_button)
        self.veterinarian_positions = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.veterinarian_positions.sizePolicy().hasHeightForWidth())
        self.veterinarian_positions.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.veterinarian_positions.setFont(font)
        self.veterinarian_positions.setObjectName("veterinarian_positions")
        self.horizontalLayout_5.addWidget(self.veterinarian_positions)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, 25, -1, 25)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.housing_acts_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.housing_acts_button.sizePolicy().hasHeightForWidth())
        self.housing_acts_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.housing_acts_button.setFont(font)
        self.housing_acts_button.setObjectName("housing_acts_button")
        self.horizontalLayout_6.addWidget(self.housing_acts_button)
        self.medical_acts_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.medical_acts_button.sizePolicy().hasHeightForWidth())
        self.medical_acts_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.medical_acts_button.setFont(font)
        self.medical_acts_button.setObjectName("medical_acts_button")
        self.horizontalLayout_6.addWidget(self.medical_acts_button)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(-1, 25, -1, 25)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.vaccines_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vaccines_button.sizePolicy().hasHeightForWidth())
        self.vaccines_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.vaccines_button.setFont(font)
        self.vaccines_button.setObjectName("vaccines_button")
        self.horizontalLayout_7.addWidget(self.vaccines_button)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        main.setCentralWidget(self.centralwidget)

        self.retranslateUi(main)
        QtCore.QMetaObject.connectSlotsByName(main)

    def retranslateUi(self, main):
        _translate = QtCore.QCoreApplication.translate
        main.setWindowTitle(_translate("main", "MainWindow"))
        self.main_label.setText(_translate("main", "Choose which table to edit:"))
        self.humans_button.setText(_translate("main", "Humans"))
        self.clients_button.setText(_translate("main", "Clients"))
        self.employees_button.setText(_translate("main", "Employees"))
        self.animals_button.setText(_translate("main", "Animals"))
        self.animal_cards_button.setText(_translate("main", "Animal cards"))
        self.housings_button.setText(_translate("main", "Housings"))
        self.clinics_button.setText(_translate("main", "Clinics"))
        self.positions_button.setText(_translate("main", "Positions"))
        self.shelter_positions_button.setText(_translate("main", "Shelter positions"))
        self.clinic_positions_button.setText(_translate("main", "Clinic positions"))
        self.veterinarian_positions.setText(_translate("main", "Veterinarian positions"))
        self.housing_acts_button.setText(_translate("main", "Housing acts"))
        self.medical_acts_button.setText(_translate("main", "Medical acts"))
        self.vaccines_button.setText(_translate("main", "Vaccines"))
